### ISSUE TITLE
非中文UNICODE字符识别有问题

### ISSUE THREAD

**Issue by blueset** [maicong/music#1]
尝试搜索
> 初音ミクの消失

被报错。

**Comment by maicong** [comment]
正则匹配的问题…… 没有匹配这些奇怪的字符……

**Comment by blueset** [comment]
建议实现unicode全语种支持。

**Comment by maicong** [comment]
■˘＿＿＿＿＿＿＿＿˘■

**Comment by maicong** [comment]
已修复：https://github.com/maicong/music/commit/4682e8c050e88b47a8160d05cf98953ac3d549be
