### ISSUE TITLE
qq音乐搜索出来的音乐音质太低

### ISSUE THREAD

**Issue by GDrain** [maicong/music#10]
<不要说话>qq音乐搜索出来只有863kb，码率24kbps，太低了吧，能否提高下音质，谢谢

顺便一提，博主的音乐歌单不错，循环了一下午233

**Comment by maicong** [comment]
已优化，可以听 320Kbps 的了。

详见：https://github.com/maicong/music/commit/678967e5b421162e7e6bf578f0743e620893046c

**Comment by maicong** [comment]
不客气
