### ISSUE TITLE
v1.4.4更新后出bug 

### ISSUE THREAD

**Issue by GDrain** [maicong/music#11]
在该版本，网易源搜索<不要说话>返回的结果是一些奇怪的歌曲。
试了下其他歌曲，也会有概率出现这个问题。

**Comment by maicong** [comment]
能不能贴个图我看下？可能搜索关键词包含了歌名、歌手和歌词。

**Comment by GDrain** [comment]
搜索的就是<不要说话>四个字，歌曲头像和歌手名都是和以前一样正常的，但就是播放的内容不对，是其他歌曲。

**Comment by maicong** [comment]
是我代码一个 BUG ，骚等我修复下。

**Comment by GDrain** [comment]
好滴，大佬辛苦了

**Comment by maicong** [comment]
已经发布了新版：[music-1.4.5](https://github.com/maicong/music/releases/tag/music-1.4.5)

**Comment by GDrain** [comment]
谢谢大佬
