### ISSUE TITLE
代理代码还没改啊。。。

### ISSUE THREAD

**Issue by xwj1612** [maicong/music#15]
原代码：
if ($args['proxy'] && define('MC_PROXY')) {
改成下面这样是没啥问题的
if ($args['proxy'] && MC_PROXY) {
因为define('MC_PROXY')始终返回true啊，判断没有意义了。。而且这时候会运行一次define()空定义，php应该还会报错吧。。。

我提过好几个月了？你是不是一直没有测试过代理功能😂

**Comment by maicong** [comment]
对，没有测试过……
大意了，少写了个d，谢谢反馈，回头改下。

**Comment by maicong** [comment]
已修复 7a6df612016423c4be7eb0c332df5541240dc321

**Comment by xwj1612** [comment]
@maicong    第一个if判断没必要呀，define('MC_PROXY')这个始终返回true并且php会报错，提示缺少第二个参数

**Comment by xwj1612** [comment]
if(define('MC_PROXY'))
echo 666;  //666

运行一下，把错误开开。。  我这边php5.5  测试

**Comment by xwj1612** [comment]
我瞎了。。。刚反应过来。。红色的是删掉的。。。打了一晚上游戏 脑子忽然有些不够用😅
