### ISSUE TITLE
网易云ERROR?

### ISSUE THREAD

**Issue by lolbob** [maicong/music#17]
搜索出的所有歌曲都有这样的错误：
歌曲名 - Error happens ╥﹏╥

其他站QQ酷狗虾米等同样歌曲可以播放，其他歌曲也没有问题.

**Comment by maicong** [comment]
我这边发现是好的呢，你能给个具体的截图吗？

![2018-01-29 09 52 03](https://user-images.githubusercontent.com/6924891/35490364-1eff592e-04da-11e8-9d39-ae9f3b4a36ca.png)

**Comment by lolbob** [comment]
![1eaa8dc1a0a88c2f9f78846e2c8bc7e3](https://user-images.githubusercontent.com/5314949/35518758-b79e0530-0512-11e8-98c5-b4fe29d5a154.png)

**Comment by maicong** [comment]
能提供下你的浏览器信息吗？品牌和版本。

**Comment by lolbob** [comment]
chrome, 63.0.3239.132 (Official Build) (64-bit)

**Comment by maicong** [comment]
不应该啊，你是使用源码自己搭建的还是在 music.2333.me 使用的？

**Comment by lolbob** [comment]
music.2333.me 用的，说不定是我在国外的关系？但是其他的都能用啊

**Comment by maicong** [comment]
嗯，对的，国外 IP 是无法播放网易云音乐的音频连接的，这个是网易那边的限制。
