### ISSUE TITLE
批量下载

### ISSUE THREAD

**Issue by upupming** [maicong/music#19]
## Bug
搜索一个歌手时，点击第二首歌曲会播放，但是上方的下载链接任然是第一首歌曲的，不变。
## 希望增加功能
搜索一个歌手时，想要下载多首歌曲就必须一首一首地点击，很不方便，可以加入批量下载功能吗？

**Comment by upupming** [comment]
发现那上面的链接是随机的，反正就是跟正在播放的音乐不对应。

**Comment by maicong** [comment]
1. `下载链接仍是第一首歌曲` 这个问题是因为当你点击第二首歌时，这首歌还在加载中并不能立即播放，所以上面的连接还是上次播放的地址，如果网速快的话，是不会出现这个问题的。我会优化下相关代码，更改下判断方式。

2. 目前这个 UI 版本，暂时不加入批量下载。这是一个测试功能，部分浏览器并不支持它。
