### ISSUE TITLE
网易云音乐所有链接失效？

### ISSUE THREAD

**Issue by htqqdd** [maicong/music#21]
刚刚开始，所有网易云音乐的搜索结果都是”Error happens ╥﹏╥“，歌名、封面、歌词都能加载，除了音乐不能播放，例如：不要说话 - Error happens ╥﹏╥。是出什么问题了吗？

**Comment by syh0304** [comment]
me too。。。。。

**Comment by maicong** [comment]
已经在 1.5.7 版本修复
