### ISSUE TITLE
网易云无法解析出音乐地址！

### ISSUE THREAD

**Issue by lbroot** [maicong/music#23]
举例：Dangerous Night   Thirty Seconds to Mars
实测发现网易的vip曲目未登录是不会返回文件地址的，希望支持带cookies解析。
因为网易客户端现在下载的文件自动加密为.ncm，还是希望能通过第三方下载mp3文件。
你懂我意思吧（疯狂暗示）

**Comment by maicong** [comment]
无法解析音频地址问题已经在 1.5.7 版本修复
