### ISSUE TITLE
咪咕音乐有问题

### ISSUE THREAD

**Issue by SuperstarSage** [maicong/music#29]

**Comment by maicong** [comment]
具体什么问题能说明下吗

**Comment by SuperstarSage** [comment]
无法解析，你试试看

**Comment by maicong** [comment]
好的呢

![qq20180302-141153](https://user-images.githubusercontent.com/6924891/36885728-b0222bfe-1e23-11e8-9995-aa0c06c7431f.png)

**Comment by SuperstarSage** [comment]
http://music.migu.cn/v2/music/song/1109450401?channelId=0010062
通过链接无法解析，其他的都可以

**Comment by maicong** [comment]
修复了 https://github.com/maicong/music/commit/c812955b5c9c8a0d9850597ca70786f5ee911d2d
