### ISSUE TITLE
关于音乐接口http类型问题

### ISSUE THREAD

**Issue by Youngxj** [maicong/music#31]
我发现QQ音乐使用的https接口，还有其他一些是用的http接口，这就导致我的站如果是https的话，http资源就加载不出来，郁闷

**Comment by maicong** [comment]
将 [core/music.php](https://github.com/maicong/music/blob/58d80ea8aff74400c325fd2f3dee3e9ba9515b20/core/music.php#L1212) 第 1212 行的 `http://` 改成 `https://`

**Comment by maicong** [comment]
全部改为 https:// 的话，在 [core/music.php](https://github.com/maicong/music/blob/58d80ea8aff74400c325fd2f3dee3e9ba9515b20/core/music.php#L1212) 搜索 `$radio_songs[]`，将里面 url 字段值用 `str_replace('http://', 'https://', $URL)` 函数替换

**Comment by maicong** [comment]
如果你嫌上面操作麻烦，可以在你的网站配置里去掉 `Content-Security-Policy` 这个 header
