### ISSUE TITLE
如何设置不自动播放？

### ISSUE THREAD

**Issue by aixiu** [maicong/music#37]
get后，能不能不自动播放？或者设置个开关。

**Comment by maicong** [comment]
如果浏览器支持自动播放是可以自动播放的，禁用掉此功能，请注释这3行

https://github.com/maicong/music/blob/58d80ea8aff74400c325fd2f3dee3e9ba9515b20/static/js/music.js#L256-L258

**Comment by aixiu** [comment]
@maicong thx.

**Comment by maicong** [comment]
您好，注释掉后是可以关闭自动播放的。

**Comment by aixiu** [comment]
成了，是我操作失误。抱歉
