### ISSUE TITLE
咪咕详情问题

### ISSUE THREAD

**Issue by yhsj0919** [maicong/music#38]
搜索接口带有播放地址,推荐用搜索的解析
现有的详情接口 有问题,部分地址会解析空,比如搜索薛之谦, 演员的地址获取不到,但是搜索的时候能获取到

http://music.migu.cn/v2/async/audioplayer/playurl/歌曲ID
如果用Id获取,上面的地址也可以,还支持320码率,搜索出来的只有64的,

**Comment by maicong** [comment]
感谢反馈，已经更新了咪咕接口，已发布版本 [1.6.0](https://github.com/maicong/music/releases/tag/music-1.6.0)

> 如果你的网站在国内，打开 [/index.php](https://github.com/maicong/music/blob/8dabb836a62332076f3cec2b24f7e99221e1880e/index.php)，将 `define('MC_INTERNAL', 0);` 修改为 `define('MC_INTERNAL', 1);`，这样就可以取到咪咕和网易云音乐的 320k 音频了。
