### ISSUE TITLE
我想调用你的接口

### ISSUE THREAD

**Issue by y249839817** [maicong/music#39]
能把接口给我下吗，我调用总是返回首页。

**Comment by y249839817** [comment]
或者 能说下 你的 实现原理吗 因为 调用接口 回到首页这是 第一次 ，不得不说 做的很好 。嘿嘿

**Comment by y249839817** [comment]
我调用你的接口不是商业用途。我也可以帮你推广，如果有人调我，我都返回你的网址

**Comment by y249839817** [comment]
我大概理解你是怎么做的，就是第一次发送请求的时候，你重定向到你的页面，然后再在你的页面发送请求
到你的后台，能分享下吗，你是怎么判断这是第一次请求还是第二次呢

**Comment by maicong** [comment]
您好，目前演示站点为了减少服务器压力，不提供 API 接口功能，并限制了一定时间内的请求次数。建议您使用源码自行搭建，以免被判定到临时黑名单。

**Comment by y249839817** [comment]
嗯  我不调用接口了 能联系下你 我想知道下实现原理

**Comment by y249839817** [comment]
好的 谢谢
