### ISSUE TITLE
QQ音乐获取到的key加上其他的值得到的QQ音乐歌曲的连接会出现403，用楼主网站的Key值复制进去便没问题，是我获得key的方法有问题吗，下面是获取Key的网站。

### ISSUE THREAD

**Issue by RayphoneChao** [maicong/music#42]
http://base.music.qq.com/fcgi-bin/fcg_musicexpress.fcg?referer=http://y.qq.com&proxy=false&json=3&guid=5150825362&format=json

**Comment by yhsj0919** [comment]
这个问题可能是获取KEY和下面解析用的参数不同意造成的,尤其User-Agent,两个接口都需要加上相同的

**Comment by RayphoneChao** [comment]
'http://dl.stream.qqmusic.qq.com/M800'+songMids[0]+'.mp3vkey='+qqMusicKey+'&guid=5150825362&fromtag=1'
我把获取的key按照这个组合起来，应该是我获取的key有问题，但是我是仿照的作者PHP源码获取key的代码,所以我就不知道哪里有问题了。
作者获取Key的方式[
                'method'     => 'GET',
                'url'        => 'http://base.music.qq.com/fcgi-bin/fcg_musicexpress.fcg',
                'referer'    => 'http://y.qq.com',
                'proxy'      => false,
                'body'       => [
                    'json'   => 3,
                    'guid'   => 5150825362,
                    'format' => 'json'
                ]
我获取key的方式
    hedaers= {'referer':'http://y.qq.com','proxy':'false','json':3,'guid':5150825362,'format':'json'}
    url='http://base.music.qq.com/fcgi-bin/fcg_musicexpress.fcg'
    response = requests.get(url,hedaers)

**Comment by yhsj0919** [comment]
https://github.com/yhsj0919/KMusic
这是我写的kotlin版本,只添加了主流网站

这里主要的问题是 "User-Agent",这个是必须添加的
val vkeyResp = get(url = "http://base.music.qq.com/fcgi-bin/fcg_musicexpress.fcg?json=3&guid=5150825362&format=json",
                    headers = mapOf("Referer" to "http://m.y.qq.com",
                            "User-Agent" to "Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1"))

**Comment by maicong** [comment]
目前 QQ 音乐使用单一 key 调用音乐链接是有些问题的，可以带上参数 `songmid ` 和 `filename`获取对应的 key。

**Comment by RayphoneChao** [comment]
我这里加入了User-Agent获取到的Key还是不对，然后我加入了songmid也没有什么起色，并且我看两位大佬的源码中请求key没有加和歌曲相关的参数啊。

**Comment by yhsj0919** [comment]
我当时也出现过403,加上User-Agent就正常了,没有加其他参数,现在没出现过问题
