### ISSUE TITLE
网页搜索一直出现  (°ー°〃) 出了点小问题，请重试

### ISSUE THREAD

**Issue by a635006175** [maicong/music#43]
(°ー°〃) 出了点小问题，请重试
(°ー°〃) 出了点小问题，请重试
怎么解决的。。。。

**Comment by maicong** [comment]
如果是演示站点提示，可能是 CDN 问题，多试几次。
如果是自行搭建站点问题，建议开启 debug 看看。

修改此行代码开启：

https://github.com/maicong/music/blob/a988ce0833ecc8c10d3fc70a327baccaa6f71a4f/index.php#L24-L25

**Comment by Rossichan** [comment]
我也出现了此问题，不知道你解决了没有，什么原因导致？
