### ISSUE TITLE
分流站点收集

### ISSUE THREAD

**Issue by maicong** [maicong/music#44]
目前演示站点因为请求数量日益增多，导致服务器偶尔处理不过来而宕机。

作为一个开源项目，维护一个站点需要一定成本。在这个大数据时代，群体大于单干。

如果您的站点使用了本源码搭建，并拥有良好的访问体验，可以留下您的网站地址，我会通过一定的规则筛选后，在演示站点加上贵站，同时您的名字会被加入到贡献者列表，当然，您也可以选择匿名。

我会在取得您的同意后，将此地址用于演示站的接口列表，在高并发的时候，会随机选择一个接口用于分流。

如果您开启了防火墙，请将 `music.2333.me` 加入到白名单。

我希望您提供的地址是**绿色**、**安全**，同时又**稳定**的。

如果您愿意共享这份资源，欢迎留下您的网站地址。

感谢！

**Comment by githubforyour** [comment]
https://music.itviki.com  欢迎访问在线音乐搜索  感谢maicong提供不错的开源项目 ！

**Comment by a635006175** [comment]
https://lovelss.club/music/             谢谢大佬 =-=

**Comment by FastChen** [comment]
https://music.nullcraft.cn/
非常感谢大佬制作的项目
回馈帮助!

**Comment by Zzm317** [comment]
https://music.loli.ren
https证书申请中（
使用腾讯cdn加速，腾讯每个月有送流量包所以用的话问题不大

**Comment by gxlu1997** [comment]
http://ww.bilibibi.ml
因为最近太忙 过几天我会将您的链接重新附上去

**Comment by gxlu1997** [comment]
http://www.bilibibi.ml
因为最近太忙 过几天我会将您的链接重新附上去，欢迎访问在线音乐搜索 感谢maicong提供不错的开源项目 ！

**Comment by haoyuliang** [comment]
http://music.bbbt.me
望采纳

**Comment by aixiu** [comment]
http://forum.ynxiu.com/music/
每次都是自己用来听歌，现在也发出来，谢谢老大的源码。

**Comment by geekglasshouse** [comment]
https://music.geekglasshouse.top
也是作为一个小项目挂在网站上，良好体验！
新加坡主机，月流量50G，用不完的，
免费用了大佬源码，回报援助大佬！
关站？这辈子都不可能的

**Comment by hongzeliang** [comment]
hongzeliang.top/music

**Comment by wrswap** [comment]
http://misic.wrs6.cn

**Comment by geekglasshouse** [comment]
获得的链接可以是https的吗。。加载小绿锁就木得了

**Comment by 2463091804** [comment]
平时自己和朋友用的
[https://y.503.one/](url) 
[https://music.503.one/](url)

**Comment by 2463091804** [comment]
@lisachensyd 抱歉，把https关了，忘说了，http访问即可

**Comment by weiyidu** [comment]
http://music.234du.com

**Comment by YSC168** [comment]
用什么将php发布到网站啊

**Comment by shenmengxi1220** [comment]
http://music.cccyun.cc/
阿里云服务器+百度云加速专业版

**Comment by maicong** [comment]
感谢 @githubforyour @a635006175 @FastChen @Zzm317 @geekglasshouse @shenmengxi1220 提供的接口，请将 `https://music.2333.me/` 加入到 `Access-Control-Allow-Origin` 列表

定位到此处：

https://github.com/maicong/music/blob/a988ce0833ecc8c10d3fc70a327baccaa6f71a4f/core/music.php#L1316

在上面一行添加：

```php
if (preg_match('/music.2333.me$/i', server('HTTP_ORIGIN'))) {
    header('Access-Control-Allow-Origin: ' . server('HTTP_ORIGIN')); 
    header('Access-Control-Allow-Methods: POST');
}
```

**Comment by Zzm317** [comment]
@maicong 已在1316行添加上述内容，请查验

**Comment by maicong** [comment]
@Zzm317 `Access-Control-Allow-Methods` 我少加了个方式，你改成：
```php
header('Access-Control-Allow-Methods: POST, OPTIONS');
```

**Comment by gxlu1997** [comment]
https://www.ppyy.ooo ssl证书已经配置 自动跳转也配置了 您再重新看看

**Comment by Zzm317** [comment]
@maicong 已添加header('Access-Control-Allow-Methods: POST, OPTIONS'); cdn已部署

**Comment by maicong** [comment]
@Zzm317 尴尬，你那边还得添加个特殊头的允许。最终改成这样：

```php
if (preg_match('/music.2333.me$/i', server('HTTP_ORIGIN'))) {
    header('Access-Control-Allow-Origin: ' . server('HTTP_ORIGIN')); 
    header('Access-Control-Allow-Methods: POST, OPTIONS');
    header('Access-Control-Allow-Headers: DNT, User-Agent, X-Requested-With, If-Modified-Since, Cache-Control, Content-Type, Range');

    if (server('REQUEST_METHOD') === 'OPTIONS') {
        header('Access-Control-Max-Age: 1728000');
        header('Content-Length: 0');
        header("HTTP/1.1 204 No Content");
        exit();
    }

    header('Access-Control-Expose-Headers: Content-Length, Content-Range');
}
```

**Comment by Zzm317** [comment]
@maicong 哇=-= 加了 我去部署下cdn

**Comment by maicong** [comment]
@Zzm317 

**405 Method Not Allowed**，还是不行，我再研究下。

> Access to XMLHttpRequest at 'https://music.loli.ren/' from origin 'https://music.2333.me' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: It does not have HTTP ok status.

**Comment by Zzm317** [comment]
@maicong 你邮箱多少 我电邮给你ip你host试下

**Comment by zuiaixs** [comment]
http://music.93jw.com/已经搭建好，感谢大佬分享的音乐搜索源码

**Comment by ithou** [comment]
感谢作者~ https://music.ithee.cn

**Comment by tianmoyun** [comment]
感谢大佬分享，网站搭建好，jx.ospho.cn/music

**Comment by tianmoyun** [comment]
http://jx.ospho.cn，网站已搭建好，感谢大佬分享

**Comment by tianmoyun** [comment]
http://jx.ospho.cn/music，网站已搭建好，感谢大佬分享
