### ISSUE TITLE
老大~~~怎么搜索木有反应呢

### ISSUE THREAD

**Issue by wggwcn** [maicong/music#5]

**Comment by walaoaaa1234** [comment]
https://maicong.me/msg
MaiCong博主
June 2nd, 2017 at 10:32 am
被人大流量攻击了。

**Comment by maicong** [comment]
昨天被人大流量攻击，IP 暂时被封了，预计晚上恢复吧。

**Comment by maicong** [comment]
稍等一会，我再弄一台服务器安装。
