### ISSUE TITLE
可以支持一下 蜻蜓fm吗？

### ISSUE THREAD

**Issue by liguge** [maicong/music#6]

**Comment by liguge** [comment]
网易云的付费歌曲 和下架歌曲都不行 这个有办法解决吗？

**Comment by maicong** [comment]
付费音乐还是开 VIP 吧，蜻蜓 FM 我去看看，有接口的话就加上。

**Comment by liguge** [comment]
@maicong  主要是下架的歌曲 付费vip已经是了  这个比较难受~

**Comment by maicong** [comment]
@liguge 下架的可以换个平台听

**Comment by xwj1612** [comment]
@maicong 网易云付费那个，我写过个试听代码。。下载的话没有扩展名，因为是旧版客户端老接口，在线播放没问题，有需要就看看吧
思路来源找不到了。。需要的可以搜一下代码headers……

测试付费ID 426881487 下线的不知道id，没测试
//先获取音乐id
        $url = "http://music.163.com/api/song/detail/?ids=[$id]";
        $data = file_get_contents($url);
        global $json;
        $json = json_decode($data, true);
          if (!empty($json['songs']['0']['album']['id'])) {
            $aid = $json['songs']['0']['album']['id'];
          }
//取到专辑id^^^^
          $url = "http://music.163.com/api/album/$aid";
          $headers = array('Cookie:appver=1.5.0.75771', 'Referer:http://music.163.com');
          $data = curl($url, $headers);
          $data = json_decode($data, true);
          //echo var_dump($data);
          $songs = $data['album']['songs'];
//在这个专辑接口里遍历获取相同的音乐id
          for ($i = 0;$i < count($songs);$i++) {
            if ($songs[$i]['id'] == $id) {
              echo str_replace('http://m', 'http://p', $songs[$i]['mp3Url']);
            }
          }

**Comment by xwj1612** [comment]
curl function忘了贴了。大概就是通用的那种。。好像需要大陆ip  我看我代码用proxy了...

**Comment by maicong** [comment]
@xwj1612 讲真，付费的要么换个平台要么买个会员吧。
