### ISSUE TITLE
你好 我在本地搭建好之后，出现错误

### ISSUE THREAD

**Issue by feiyangbeyond** [maicong/music#64]
你好！我在本地搭建好之后，出现小问题。
当我在搜索音乐名称：”不要说话”时，提示(°ー°〃) 出了点小问题，请重试、
尝试了其他的所有之后都是这个提示 ，请问是怎么回事呢？

**Comment by maicong** [comment]
查看下是不是环境问题？浏览器抓包看看是什么报错信息。
