### ISSUE TITLE
要是支持下载高品质或无损音乐那就好了

### ISSUE THREAD

**Issue by zuiaixs** [maicong/music#8]
提供个直接下载的按钮，提高用户体验，要是支持下载高品质或无损音乐那就更好了

**Comment by maicong** [comment]
:-D 我有个新版本的规划，里面有音质选择。但是...

没做完，工程暂停了。

**Comment by maicong** [comment]
有高品质的已经支持了，无损的话虽然接口里有，但我还是建议需要付费的就付费，需要会员就会员。
